import styles from './Stack.module.scss'
type Props = {}

export default function Stack({}: Props) {
  return (
    <div className={styles.Stack}>
        <div className={styles.stack_list}>
            <img src="https://img.icons8.com/color/48/000000/html-5--v1.png" alt="html"/>
            <img src="https://img.icons8.com/color/48/000000/html-5--v1.png" alt="html"/>
            <img src="https://img.icons8.com/color/48/000000/html-5--v1.png" alt="html"/>
            <img src="https://img.icons8.com/color/48/000000/html-5--v1.png" alt="html"/>
            <img src="https://img.icons8.com/color/48/000000/html-5--v1.png" alt="html"/>
            <img src="https://img.icons8.com/color/48/000000/html-5--v1.png" alt="html"/>
        </div>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla sapiente, repellat nobis ullam culpa, nesciunt inventore iure amet commodi itaque suscipit, a magni? Illo aliquid earum dolorum aut assumenda magnam explicabo? Fugiat, est debitis eligendi beatae necessitatibus alias, ab pariatur perspiciatis itaque officiis sapiente eius corrupti, quos consequatur explicabo doloremque id tenetur tempore iste. Fugiat nam facere itaque inventore quas alias ex, at, quae atque nemo, reiciendis aliquid iusto eius dolore suscipit dolores temporibus ullam ipsum dignissimos dicta. Cumque, cum. Mollitia excepturi, aperiam doloremque sed perferendis placeat saepe pariatur voluptates, voluptate vel nostrum dolorum reprehenderit debitis dolor distinctio molestias odit libero harum iure quas sint nulla adipisci? Possimus reiciendis cumque enim accusamus soluta quae aliquam praesentium odio recusandae corrupti</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla sapiente, repellat nobis ullam culpa, nesciunt inventore iure amet commodi itaque suscipit, a magni? Illo aliquid earum dolorum aut assumenda magnam explicabo? Fugiat, est debitis eligendi beatae necessitatibus alias, ab pariatur perspiciatis itaque officiis sapiente eius corrupti, quos consequatur explicabo doloremque id tenetur tempore iste. Fugiat nam facere itaque inventore quas alias ex, at, quae atque nemo, reiciendis aliquid iusto eius dolore suscipit dolores temporibus ullam ipsum dignissimos dicta. Cumque, cum. Mollitia excepturi, aperiam doloremque sed perferendis placeat saepe pariatur voluptates, voluptate vel nostrum dolorum reprehenderit debitis dolor distinctio molestias odit libero harum iure quas sint nulla adipisci? Possimus reiciendis cumque enim accusamus soluta quae aliquam praesentium odio recusandae corrupti. Quo ratione mollitia beatae ipsum at est. Porro sint totam impedit et voluptas iste distinctio nemo dolorum ab quam asperiores nesciunt voluptatibus, soluta eligendi, reprehenderit illo ducimus magni. Molestiae aspernatur exercitationem, optio alias aliquam tempore deserunt distinctio corrupti provident voluptate quibusdam deleniti consequatur est, fuga vero temporibus. Ut consequatur eaque, aspernatur cumque nobis possimus rerum voluptate commodi aliquam veritatis corporis ad, culpa officia facere ratione ipsa voluptas rem. Adipisci nulla ullam rerum aliquam iusto maxime quaerat quo omnis modi, porro ducimus!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla sapiente, repellat nobis ullam culpa, nesciunt inventore iure amet commodi itaque suscipit, a magni? Illo aliquid earum dolorum aut assumenda magnam explicabo? Fugiat, est debitis eligendi beatae necessitatibus alias, ab pariatur perspiciatis itaque officiis sapiente eius corrupti, quos consequatur explicabo doloremque id tenetur tempore iste. Fugiat nam facere itaque inventore quas alias ex, at, quae atque nemo, reiciendis aliquid iusto eius dolore suscipit dolores temporibus ullam ipsum dignissimos dicta. Cumque, cum. Mollitia excepturi, aperiam doloremque sed perferendis placeat saepe pariatur voluptates, voluptate vel nostrum dolorum reprehenderit debitis dolor distinctio molestias odit libero harum iure quas sint nulla adipisci? Possimus reiciendis cumque enim accusamus soluta quae aliquam praesentium odio recusandae corrupti. Quo ratione mollitia beatae ipsum at est. Porro sint totam impedit et voluptas iste distinctio nemo dolorum ab quam asperiores nesciunt voluptatibus, soluta eligendi, reprehenderit illo ducimus magni</p>
    </div>
  )
}